apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers-app
  namespace: app
subjects:
  - kind: Group
    name: developers
    namespace: app
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developers-app
  apiGroup: rbac.authorization.k8s.io
