name: Deploy to EKS and ECR

on:
  push:
    branches:
      - main  # Change to your main branch name
env:
  # TF_LOG: INFO
  AWS_ACCOUNT_NUMBER: 712699700534

defaults:
  run:
    shell: bash
    working-directory: ./
permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0' # default is latest stable
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Change to your AWS region

      - name: Deploy to EKS
        run: |
          kubectl apply -f sudoku-solver-deployment.yaml -n dev
          kubectl apply -f sudoku-solver-service.yaml -n dev
          kubectl apply -f sudoku-solver-ingress.yaml -n dev
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
