name: Deploy EKS Cluster

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Adjust to your desired Terraform version

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform changes
        run: terraform apply -auto-approve

      - name: Save kubeconfig
        run: terraform output kubeconfig > kubeconfig.yml

      - name: Configure kubectl
        run: |
          kubectl --kubeconfig=kubeconfig.yml config set-cluster mycluster --server=$(terraform output cluster_endpoint) --insecure-skip-tls-verify=true

      - name: Build Docker image
        run: docker build -t sudoku-solver-app .

      - name: Retrieve ECR login credentials
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 712699700534.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image
        run: docker tag sudoku-solver-app:latest 712699700534.dkr.ecr.us-east-1.amazonaws.com/sudoku-solver-app:latest

      - name: Push Docker image to ECR
        run: docker push 712699700534.dkr.ecr.us-east-1.amazonaws.com/sudoku-solver-app:latest

      - name: Deploy to EKS
        run: |
          kubectl apply -f sudoku-solver-deployment.yaml
          kubectl apply -f sudoku-solver-service.yaml

      - name: Wait for rollout to complete
        run: |
          kubectl rollout status deployment/sudoku-solver-deployment

      - name: Update Kubernetes Ingress
        run: |
          kubectl apply -f sudoku-solver-ingress.yaml
