name: Deploy to EKS

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: eu-north-1

      - name: Build and push Docker image
        run: |
          docker build -t sudoku-solver-app:v1 .
          docker tag sudoku-solver-app:v1 712699700534.dkr.ecr.eu-north-1.amazonaws.com/sudoku-solver-app:v1
          docker push 712699700534.dkr.ecr.eu-north-1.amazonaws.com/sudoku-solver-app:v1

      - name: Deploy to EKS
        run: |
          kubectl apply -f sudoku-solver-deployment.yaml
          kubectl apply -f sudoku-solver-service.yaml

      - name: Wait for rollout to complete
        run: |
          kubectl rollout status deployment/sudoku-solver-deployment

      - name: Update Kubernetes Ingress
        run: |
          kubectl apply -f sudoku-solver-ingress.yaml

