name: Deploy EKS Cluster

on: 
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the deployment from
    paths:
      - "iac/terraform/vpc/*"
      - "iac/terraform/vpc/dev/**"
      - "iac/terraform/Eks/*"

env:
  # TF_LOG: INFO
  AWS_ACCOUNT_NUMBER: 712699700534

defaults:
  run:
    shell: bash
    working-directory: ./iac/terraform/vpc
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-north-1

      - name: Set up Terraform (vpc)
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Adjust to your desired Terraform version
      

      - name: Initialize Terraform (vpc)
        run: terraform init
      
    
      # Add the Terraform plan, Terraform Plan Status, and Terraform Apply steps here
      - name: Terraform plan
        id: plan
        run: terraform plan -target= "module.allow_eks_access_iam_policy" -no-color -input=false
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -target= "module.allow_eks_access_iam_policy" -auto-approve -input=false
