name: Deploy to EKS
on:
  push:
    branches:
      - main

    paths:
      - "iac/terraform/vpc/*"
      - "iac/terraform/vpc/dev/**"
env:
  # TF_LOG: INFO
  AWS_ACCOUNT_NUMBER: 712699700534
defaults:
  run:
    shell: bash
    working-directory: ./iac/terraform/vpc
permissions:
  contents: read
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint. New
    permissions:
      #id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
      # Add the AWS credentials configuration steps here
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION
    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-north-1


      - name: Clean up Docker build context
        run: rm -rf /var/lib/docker/tmp/buildkit-mount*
        
      - name: Build and push Docker image
        run: |
          docker build -t sudoku-solver-app:v1 .
          docker tag sudoku-solver-app:v1 712699700534.dkr.ecr.eu-north-1.amazonaws.com/sudoku-solver-app:v1
          docker push 712699700534.dkr.ecr.eu-north-1.amazonaws.com/sudoku-solver-app:v1

      - name: Deploy to EKS
        run: |
          kubectl apply -f sudoku-solver-deployment.yaml
          kubectl apply -f sudoku-solver-service.yaml

      - name: Wait for rollout to complete
        run: |
          kubectl rollout status deployment/sudoku-solver-deployment

      - name: Update Kubernetes Ingress
        run: |
          kubectl apply -f sudoku-solver-ingress.yaml

