name: Deploy to Dev Environment

on:
  push:
    branches:
      - main
    paths:
      - "iac/terraform/vpc/*"
      - "iac/terraform/vpc/dev/**"
      - "iac/terraform/Eks/*"  # Add this line to include the Eks directory

permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-north-1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: 1.4.6

      - name: Run Terraform commands
        run:
          shell: bash
          working-directory: ./iac/terraform/vpc  # Update this path if needed
          command: |
            # Add your Terraform commands here, such as:
            # terraform init
            # terraform apply -auto-approve

      - name: Build and push Docker image
        run: |
          docker build -t sudoku-solver-app:v1 .
          docker tag sudoku-solver-app:v1 712699700534.dkr.ecr.eu-north-1.amazonaws.com/sudoku-solver-app:v1
          docker push 712699700534.dkr.ecr.eu-north-1.amazonaws.com/sudoku-solver-app:v1

      - name: Deploy to EKS
        run: |
          kubectl apply -f sudoku-solver-deployment.yaml
          kubectl apply -f sudoku-solver-service.yaml

      - name: Wait for rollout to complete
        run: |
          kubectl rollout status deployment/sudoku-solver-deployment

      - name: Update Kubernetes Ingress
        run: |
          kubectl apply -f sudoku-solver-ingress.yaml

# Add more jobs or steps as needed...
