name: Deploy to EKS and ECR

on: 
  push:
    branches:
       - main  # Change to your main branch name
    paths:
       - "iac/terraform/Eks/*"
      
env:
  # TF_LOG: INFO
  AWS_ACCOUNT_NUMBER: 712699700534

defaults:
  run:
    shell: bash
    working-directory: ./
permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Change to your AWS region



      - name: Update kube config
        run: aws eks update-kubeconfig --region  eu-north-1 --name awesome_cluster 

        

      - name: Apply RBAC configurations
        run: |
          kubectl apply -f rbcrole.yaml
          kubectl apply -f rbforpocnamespace.yaml
          kubectl apply -f rolebend.yaml
